StringTable strings = new StringTable();

class StringTable {
  StringTable._internal();
  factory StringTable() => StringTable._internal();

  static Map<String, String> table;
  String rupee = "₹";

  String get(String title) {
    return table[title] == null ? "" : table[title];
  }

  set() {
    table = {
      "CRICKET": "Cricket",
      "FOOTBALL": "Football",
      "UPCOMING": "Upcoming",
      "RESULT": "Result",
      "LIVE": "Live",
      "COMING_SOON": "Coming soon",
      "ALL_SERIES": "All series",
      "CONTESTS": "Contests",
      "CONTEST_CODE": "Contest code",
      "MY_CONTESTS": "My contests",
      "ADD_CASH": "Add cash",
      "EARN_CASH": "Earn cash",
      "KABADDI": "Kabaddi",
      "AMOUNT_SHOULD_DISTRIBUTED": "Whole amount should be distrubuted.",
      "IN_PROGRESS": "In progress",
      "COMPLETED": "Completed",
      "DO_U_W_EXIT": "Do you want to exit an app",
      "OK": "Ok",
      "CANCEL": "Cancel",
      "CLOSE": "Close",
      "RETRY": "Retry",
      "SAVE": "Save",
      "SEARCH": "Search",
      "NO_COMPLETED_CONTEST": "There are no completed contests.",
      "NO_RUNNING_CONTEST": "There are no running contests.",
      "NO_UPCOMING_CONTEST": "There are no upcoming contests.",
      "NO_COMPLETED_MATCHES": "There are no completed matches.",
      "NO_RUNNING_MATCHES": "There are no running matches.",
      "NO_UPCOMING_MATCHES": "There are no upcoming matches.",
      "UPCOMING_MATCHES": "Upcoming matches",
      "LIVE_MATCHES": "Live matches",
      "COMPLETED_MATCHES": "Completed matches",
      "ACCOUNT_BLOCKED": "Account blocked",
      "AC_BLOCKED_MSG":
          "Your account has been blocked.\nPlease contact us at support@playfantasy.com to get more information.",
      "ACCOUNT_CLOSED": "Accout closed",
      "AC_CLOSED_MSG":
          "Your account has been closed.\nPlease contact us at support@playfantasy.com to get more information.",
      "AGE_LESS_MSG": "Your age is less than 18.\nYou cannot add any cash.",
      "STATE_BLOCKED_MSG":
          "You are from a blocked state.\nHence, you cannot add any cash.",
      "NOT_IN_INDIA_MSG": "You are not playing from India",
      "N_I_A": "Not in india",
      "NOT_ALLOWED": "Not allowed",
      "CONTEST_FOR_NEW":
          "Contest is for only new users. You have already played contest(s).",
      "STATE_DOB_UPDATED": "State and Date of birth updated successfully.",
      "SELECT_DOB": "Please select date of birth.",
      "NOT_VERIFIED": "User is not verified.",
      "PLAYER_SELECTION_LIMIT": "You can't choose more than \$limit players.",
      "PLAYER_CREDITS_LIMIT": "You can't choose more than \$limit credits.",
      "FOREIGN_PLAYER_LIMIT":
          "You can't choose more than \$limit foreign players.",
      "SINGLE_TEAM_PLAYER_LIMIT":
          "You can't choose more than \$limit players from one team.",
      "PLAYER_STYLE_LIMIT": "You can't choose more than \$limit \$label.",
      "PLAYER_STYLE_MIN_LIMIT": "You can't choose more than \$limit \$label.",
      "DREAM_TEAM_MSG":
          "Plese select \$count more players to create your dream team.",
      "STYLE_MAX_COUNT": "Only \$count \$style allowed.",
      "STYLE_MIN_COUNT": "Only \$count \$style allowed.",
      "TOTAL_PRIZE": "Total prize",
      "WINNERS": "Winners",
      "BEST_TEAM": "Best team",
      "RANK": "Rank",
      "SCORE": "Score",
      "CREATE_CONTEST": "Create contest",
      "SEARCH_CONTEST": "Search contest",
      "SEARCH_CONTEST_WITH_CODE": "Search contest using contest code.",
      "CONTEST_NAME": "Contest name (Optional)",
      "ENTRY_FEE_NUMBER_ERROR":
          "Entry fee should be valid number between 1 to 10,000",
      "PARTICIPANTS_NUMBER_ERROR":
          "Participants should be valid number between 2 to 100",
      "TYPE": "Type",
      "ENTRY_FEE_LIMIT": "Entry fee should be between 1 to 10,000",
      "PARTICIPANTS": "Participants",
      "PARTICIPANTS_LIMIT": "Participants should be between 2 to 100.",
      "MULTY_ENTRY": "Multi entry",
      "NUMBER_OF_PRIZE": "Number of prizes",
      "CREATE_CONTEST_TOOLTIP":
          "Ceate private contest and play with your friends.",
      "CREATE_TEAM": "Create team",
      "CASH": "Cash",
      "PRACTICE": "Practice",
      "AVG_CREDITS": "AVG. CREDITS",
      "PICK": "Pick",
      "PLAYERS": "Players",
      "CREDITS": "Credits",
      "CHOOSE_CAPTAIN": "Choose captain",
      "SAVE_TEAM_ERROR": "Getting error while saving team.",
      "UPDATE_TEAM_ERROR": "Getting error while updating team.",
      "CONTEST_FILTER": "Contest filter",
      "TEAMS_NOT_AVAILABLE": "No teams available for this match.",
      "CAPTAIN": "Captain",
      "V_CAPTAIN": "Vice captain",
      "AND": "And",
      "JOIN_CONTEST": "Join Contest",
      "BONUS": "Bonus ",
      "ENTRY_FEE": "Entry fee",
      "BONUS_USABLE": "Usable bonus",
      "SELECT_TEAM": "Select team",
      "LEADERBOARD": "Leaderboard",
      "SAVE_TEAM": "Save team",
      "CONTEST_DETAILS": "Contest details",
      "NO_OF_WINNERS": "Number of winners.",
      "USE_BONUS":
          "You can use \$bonusPercent % of entry fee amount from bonus.",
      "CAPTAIN_VCAPTAIN_SELECTION":
          "Captain and vice captain selection is necessary to save team.",
      "PERCENT_BONUS_ALLOWED": "% bonus allowed.",
      "PARTICIPATE_WITH": "You can participate with \$count different teams.",
      "MAXIMUM_ENTRY": "Maximum \$count entries allowed.",
      "NO_JOINED":
          "No teams joined yet.\nBecome first player to join this contest.",
      "PRIZE": "Prize",
      "SWITCH": "Switch",
      "JOINED": "Joined",
      "TRANSACTION_FAILED": "Your transaction of ₹\$amount has been failed !",
      "TRANSACTION_DATE": "Transaction date ",
      "ORDER_ID": "Order id",
      "FUTURE_REFERENCE":
          "(For future reference in case amount has been debited from account)",
      "TRANSACTION_SUCCESS": "Transaction success!!",
      "AMOUNT_ADDED": "Amount added",
      "AMOUNT": "Amount",
      "UPDATED_BALANCE": "Updated balance",
      "HOW_TO_PLAY": "Help - How to play",
      "PRIZE_STRUCTURE": "Prize structure",
      "PRIZE_STRUCTURE_TEXT_1":
          "Actual prize structure may vary based on the number of teams joined.",
      "PRIZE_STRUCTURE_TEXT_2": "Check FAQ's for further details.",
      "PRIZE_STRUCTURE_TEXT_3":
          "As per government regulation, 30.9% of tax will be deduct for winings above rs. 10,000.",
      "MY_TEAMS": "My teams",
      "SWITCH_TEAM": "Switch Team",
      "NAME": "Name",
      "SERIES_SCORE": "Series score",
      "APP_CLOSE_TITLE": "Are you sure?",
      "YES": "Yes",
      "NO": "No",
      "CONFIRMATION": "Confirmation",
      "CASH_TO_PAY": "Cash to be paid",
      "DETAILS": "Details",
      "SUBMIT": "Submit",
      "STATE": "State",
      "DOB": "Date of birth",
      "INSUFFICIENT_FUND": "Insufficient funds!!",
      "INSUFFICIENT_FUND_MSG": "Please deposit funds to join cash contest!!",
      "DEPOSIT": "Deposit",
      "ALERT": "Alert",
      "TEAMS": "Teams",
      "CREATE_TEAM_WARNING":
          "No team created for this match. Please create one to join contest.",
      "CREATE": "Create",
      "ACCOUNT_VERIFICATION": "Account verification",
      "VERIFY": "Verify",
      "EMAIL": "E-mail",
      "MOBILE": "Mobile",
      "KYC": "KYC (ID and address verification)",
      "SEND_OTP": "Send OTP",
      "UPLOAD": "Upload",
      "WINNINGS": "Winnings",
      "WINNING_PERCENT": "Winning %",
      "TOTAL_WINNINGS": "Total winnings",
      "NOTES": "Notes",
      "WELCOME_TO_FANTASY": "Welcome to Play Fantasy,",
      "SIGN_IN_TO_CONTINUE": "Sign in to continue",
      "GOOGLE": "Google",
      "FACEBOOK": "Facebook",
      "OR": "Or",
      "USERNAME": "Username",
      "EMAIL_OR_MOBILE": "E-mail ID or mobile",
      "EMAIL_OR_MOBILE_ERROR": "Please enter E-mail ID or mobile.",
      "VALID_EMAIL_OR_MOBILE_ERROR": "Please enter valid E-mail ID or mobile.",
      "PASSWORD": "Password",
      "INVALID_USERNAME_PASSWORD": "Invalid username and/or password.",
      "USERNAME_ERROR": "Please enter username or E-mail ID or mobile.",
      "EMAIL_MIN_LENGTH_FAIL": "Please enter valid email.",
      "PASSWORD_MIN_LENGTH_FAIL": "Password should have atleast 6 characters.",
      "PASSWORD_ERROR": "Please enter Password",
      "FORGOT_PASSWORD": "Forgot password ?",
      "SIGNIN": "Sign in",
      "SIGNUP": "Sign up",
      "DONT_HAVE_ACCOUNT": "Don't have an account ?",
      "FEW_SEC_AWAY": "You are few seconds away",
      "HAVE_REFERRAL_CODE": "Have a referral code ?",
      "APPLY_NOW": "Apply now",
      "BY_REGISTERING": "By signing up, You agree to our",
      "TERMS_AND_CONDITION": "Terms and conditions",
      "REFERRAL_CODE": "Referral code",
      "FORGOT_PASS_TITLE": "Forgot password",
      "FORGOT_PASS_EMAIL":
          "Please enter E-mail ID or Mobile provided while registering with us.",
      "ENTER_OTP": "Enter OTP",
      "ENTER_OTP_ERROR": "OTP is required.",
      "NEW_PASSWORD": "New password",
      "NEW_PASSWORD_ERROR": "New password is required",
      "REENTER_PASSWORD": "Re-enter password",
      "REENTER_PASSWORD_ERROR": "Re-enter password is required",
      "PASSWORD_NOT_MATCH": "Password doesn't match.",
      "MIN_CHARS_PASSWORD": "Minimum 6 characters required.",
      "LINK_SENT":
          "Link to reset password is sent to your Email. Click on the link to reset.",
      "PASSWORD_CHANGED": "Password changed successfully",
      "EARN_CASH_TITLE": "Invite & earn",
      "FRIEND_SIGNUP_TEXT":
          "When a friend signs up with your referral code, he will get ₹",
      "VERIFY_EMAIL_MOBILE":
          "Verify your email and mobile number and share referral code with your friends.",
      "FRIEND_MOBILE_VERIFIED":
          "Make sure your friend also verifies his email and mobile number.",
      "USER_GETS_BONUS_TEXT_1": "You will get ₹",
      "USER_GETS_BONUS_TEXT_2":
          "into your unreleased bonus, Which will be released in packets based on your friend's spendings.",
      "EARN_RS": "Share and earn ₹",
      "GIVE_RS": "Give ₹",
      "COPIED": "Copied to clipboard",
      "COPY_CODE": "Copy code",
      "SHARE_NOW": "Share now",
      "FROM": "From",
      "TO": "To",
      "SWITCH_FROM": "You are switching team from",
      "SOMETHING_WENT_WRONG":
          "Something went wrong please check your inputs or internet connection.",
      "REQUEST_OTP": "Request OTP",
      "OTP_SENT": "OTP to reset password is sent to your mobile.",
      "PASSWORD_SHOULD": "Password should have a ",
      "MIN_CHAR": "minimum of 8 characters, ",
      "ATLEAST_NUMBER": "Atleast 1 number, ",
      "ATLEAST_ALPHABET": "Atleast 1 alphabet and ",
      "ATLEAST_SPECIAL_CHARACTER": "Atleast 1 special character.",
      "PASSWORD_CONSTRAINT_NOT_MATCHED":
          "Please make sure all password constraints are matched.",
      "SWITCH_TEAM_NOT_AVAIL": "No team available to switch team.",
    };
  }
}
