StringTable strings = new StringTable();

class StringTable {
  StringTable._internal();
  factory StringTable() => StringTable._internal();

  static Map<String, String> table;
  String rupee = "₹";

  String get(String title) {
    return table[title] == null ? "" : table[title];
  }

  set() {
    table = {
      "CRICKET": "Cricket",
      "FOOTBALL": "Football",
      "UPCOMING": "Upcoming",
      "RESULT": "Result",
      "LIVE": "Live",
      "COMING_SOON": "Coming soon",
      "ALL": "All",
      "SERIES": "Series",
      "CONTEST_CODE": "Contest code",
      "MY_CONTESTS": "My contests",
      "ADD_CASH": "Add cash",
      "EARN_CASH": "Earn cash",
      "NO_MATCHES": "There are no ~ matches",
      "KABADDI": "Kabaddi",
      "MATCHES": "Matches",
      "MY_PROFILE": "My profile",
      "MY_ACCOUNTS": "My accounts",
      "LOGOUT": "Logout",
      "PRIVACY_POLICY": "Privacy policy",
      "TC": "Terms and conditions",
      "ABOUT_US": "About us",
      "BLOG": "Blog",
      "FORUM": "Forum",
      "SUPPORT": "Support",
      "HELP": "Help",
      "SCORING_SYSTEM": "Scoring system",
      "B_A_PARTNER": "Become a partner",
      "CHANGE_LANG": "Change language",
      "WITHDRAW_CASH": "Withdraw cash",
      "IN_PROGRESS": "In progress",
      "COMPLETED": "Completed",
      "DO_U_W_EXIT": "Do you want to exit an app",
      "OK": "Ok",
      "CANCEL": "Cancel",
      "EXIT": "Exit",
      "CHANGE": "Change",
      "SELECT_LANGUAGE": "Select language",
      "ACCOUNT_BLOCKED": "Account blocked",
      "AC_BLOCKED_MSG":
          "Your account has been blocked.\nPlease contact us at support@playfantasy.com to get more information.",
      "ACCOUNT_CLOSED": "Accout closed",
      "AC_CLOSED_MSG":
          "Your account has been closed.\nPlease contact us at support@playfantasy.com to get more information.",
      "AGE_LESS_MSG": "Your age is less than 18.\nYou cannot add any cash.",
      "STATE_BLOCKED_MSG":
          "You are from a blocked state.\nHence, you cannot add any cash.",
      "NOT_IN_INDIA_MSG": "You are not playing from India",
      "N_I_A": "Not in india",
      "MATCH": "Match",
      "NORMAL": "Normal",
      "FANTASY": "Fantasy",
      "PRIZE_MONEY": "Prize money",
      "N_O_WINNERS": "No.Of winners",
      "TEAMS_JOINED": "Teams joined",
      "FULL": "Full",
      "JOIN": "Join",
      "JOIN+": "Join +",
      "INVITE": "Invite",
      "POPULAR": "Popular",
      "TOTAL_PRIZE": "Total prize",
      "WINNERS": "Winners",
      "YOUR_BEST_TEAM": "Your best team",
      "RANK": "Rank",
      "SCORE": "Score",
      "YOU_WON": "You Won -",
      "CREATE_CONTEST": "Create contest",
      "CONTEST_NAME": "Contest name (Optional)",
      "ENTRY_FEE_NUMBER_ERROR":
          "Entry fee should be valid number between 1 to 10,000",
      "PARTICIPANTS_NUMBER_ERROR":
          "Participants should be valid number between 2 to 100",
      "TYPE": "Type",
      "ENTRY_FEE_LIMIT": "Entry fee should be between 1 to 10,000",
      "PARTICIPANTS": "Participants",
      "PARTICIPANTS_LIMIT": "Participants should be between 2 to 100.",
      "MULTY_ENTRY": "Multi entry",
      "NUMBER_OF_PRIZE": "Number of prizes",
      "CREATE_CONTEST_TOOLTIP":
          "Ceate private contest and play with your friends.",
      "CREATE_TEAMS": "Create teams",
      "CREATE_TEAM_B_JC": "Create your Team before joining contest.",
      "CREATE_TEAM": "Create team",
      "MATCH_LIVE_CANNOT_CC": "Match is live, You can not create contest now.",
      "DATA_N_LOADED": "Data not loaded",
      "NO_CONTEST": "No ~ contests",
      "CASH": "Cash",
      "PRACTICE": "Practice",
      "LIST_OF_CONTESTS": "List of contests",
      "INNINGS": "Innings",
      "PLAYER_SELECTED": "Player selected",
      "C_LEFT": "Credits Left",
      "AC_PP": "Avg. credits / Players",
      "PICK": "PICK",
      "P_T_CC": "Proceed to choose captains",
      "PLAYERS": "Players",
      "CREDITS": "Credits",
      "CHOSE_CAPTAIN": "Choose captain",
      "P_C_MP_F_DT": "Please choose ~ more players to complete your dream team",
      "P_C_P_F_DT": "Please choose ~ players to complete your dream team",
      "MIN_XYZ_TBS": "Minimum ~ ~ to be selected",
      "Y_C_C_MORE_T": "You can\'t choose more than ~ ~.",
      "F_PLAYERS": "foreign players",
      "P_PER_TEAM": "players from one team",
      "MINI_XYZ_SELECTED": "Minimum ~ ~ should be selected",
      "CAPTAIN": "Captain",
      "V_CAPTAIN": "V.Captain",
      "PLEASE_SELECT": "Please select",
      "AND": "And",
      "JOIN_CONTEST": "Join Contest",
      "CASH_BALANCES": "Cash balance",
      "BONUS": "Bonus ",
      "ENTRY_FEE": "Entry fee",
      "BONUS_USABLE": "Usable bonus",
      "SELECT_TEAM": "Select team",
      "VS": "vs",
      "Y_H_NO_CONTEST": "You have no ~ Contests.",
      "J_B_M": "Join the below matches.",
      "SAVE_TEAM": "Save Team",
      "CONTEST_ARC_MSG":
          "Current contest is archived. You will be redirected to ",
      "TEAMS_NOT_UPDATED":
          "Teams are not yet updated. Please try after some time.",
      "CONTEST_DETAILS": "Contest Details",
      "TEAM": "Team",
      "PRIZE": "Prize",
      "SWITCH": "Switch",
      "P_G_E_CON_N_F": "Prize is Guaranteed even if contest is not filled",
      "M_NO_OF_ENTRIES": "Max number of Entries in this contest",
      "U_BONUS_USE": "upto ~ % of bonus can be used*",
      "PRIZE_STRUCTURE": "Prize structure",
      "TOTAL_PRIZE_AMOUNT": "Total Prize Amount ",
      "B_S_PRIZE_BRKUP": "prize breakup for ~ winners is shown below",
      "PRIZE_AMOUNT": "Prize Amount",
      "PRIZE_STRUCTURE_TEXT_1":
          "Actual prize structure may vary based on the number of teams joined.",
      "PRIZE_STRUCTURE_TEXT_2": "Check FAQ's for further details.",
      "PRIZE_STRUCTURE_TEXT_3":
          "As per government regulation, 30.9% of tax will be deduct for winings above rs. 10,000.",
      "EDIT": "Edit",
      "CLONE": "Clone",
      "MY_TEAMS": "My Teams",
      "ENTRY_CLOSED": "Entry Closed",
      "SWITCH_TEAM": "Switch Team",
      "MSG_SWITCH_TEAM": "You are switching your team from ~ to",
      "VIEW": "VIEW",
      "Wicket Keeper": "Wicket Keeper",
      "Batsman": "Batsman",
      "Bowler": "Bowler",
      "All Rounder": "All Rounder",
      "Goalkeeper": "Goalkeeper",
      "Defender": "Defender",
      "Midfielder": "Midfielder",
      "Forward": "Forward",
      "Raider": "Raider",
      "All-Rounder": "All-Rounder",
      "AGE_LESS_MSG_ADD_CASH":
          "Your age is less than 18.\nYou cannot add any cash.",
      "STATE_BLOCKED_MSG_ADD_CASH":
          "You are from a blocked state.\nHence, you cannot add any cash.",
      "AGE_LESS_MSG_WITHDRAW":
          "Your age is less than 18.\nYou cannot withdraw any cash.",
      "STATE_BLOCKED_MSG_WITHDRAW":
          "You are from a blocked state.\nHence, you cannot withdraw any cash.",
      "AGE_LESS_MSG_CASH_GAME":
          "Your age is less than 18.\nYou cannot play cash game.",
      "STATE_BLOCKED_MSG_CASH_GAME":
          "You are from a blocked state.\nHence, you cannot play cash game.",
      "APP_CLOSE_TITLE": "Are you sure?",
      "YES": "Yes",
      "NO": "No",
      "CONFIRMATION": "Confirmation",
      "CASH_TO_PAY": "Cash to be paid",
      "DETAILS": "Details",
      "SUBMIT": "Submit",
      "STATE": "State",
      "DOB": "Date of birth",
      "INSUFFICIENT_FUND": "Insufficient funds!!",
      "INSUFFICIENT_FUND_MSG": "Please deposit funds to join cash contest!!",
      "DEPOSIT": "Deposit",
      "ALERT": "Alert",
      "CREATE_TEAM_WARNING":
          "No team created for this match. Please create one to join contest.",
      "CREATE": "Create",
      "ACCOUNT_VERIFICATION": "Account verification",
      "VERIFY": "Verify",
      "EMAIL": "E-mail",
      "MOBILE": "Mobile",
      "KYC": "KYC (ID and address verification)",
      "SEND_OTP": "Send OTP",
      "UPLOAD": "Upload",
      "WINNINGS": "Winnings",
      "TOTAL_WINNINGS": "Total winnings",
      "NOTES": "Notes",
      "WELCOME_TO_FANTASY": "Welcome to Play Fantasy,",
      "SIGN_IN_TO_CONTINUE": "Sign in to continue",
      "GOOGLE": "Google",
      "FACEBOOK": "Facebook",
      "OR": "Or",
      "USERNAME": "Username",
      "EMAIL_OR_MOBILE": "E-mail ID or mobile",
      "EMAIL_OR_MOBILE_ERROR": "Please enter E-mail ID or mobile.",
      "VALID_EMAIL_OR_MOBILE_ERROR": "Please enter valid E-mail ID or mobile.",
      "PASSWORD": "Password",
      "INVALID_USERNAME_PASSWORD": "Invalid username and/or password.",
      "USERNAME_ERROR": "Please enter username or E-mail ID or mobile.",
      "EMAIL_MIN_LENGTH_FAIL": "Please enter valid email.",
      "PASSWORD_MIN_LENGTH_FAIL": "Password should have atleast 6 characters.",
      "PASSWORD_ERROR": "Please enter Password",
      "FORGOT_PASSWORD": "Forgot password ?",
      "SIGNIN": "Sign in",
      "SIGNUP": "Sign up",
      "DONT_HAVE_ACCOUNT": "Don't have an account ?",
      "FEW_SEC_AWAY": "You are few seconds away",
      "HAVE_REFERRAL_CODE": "Have a referral code ?",
      "APPLY_NOW": "Apply now",
      "BY_REGISTERING": "By signing up, You agree to our",
      "TERMS_AND_CONDITION": "Terms and conditions",
      "REFERRAL_CODE": "Referral code",
      "FORGOT_PASS_TITLE": "Forgot password",
      "FORGOT_PASS_EMAIL":
          "Please enter E-mail ID or Mobile provided while registering with us.",
      "ENTER_OTP": "Enter OTP",
      "ENTER_OTP_ERROR": "OTP is required.",
      "NEW_PASSWORD": "New password",
      "NEW_PASSWORD_ERROR": "New password is required",
      "REENTER_PASSWORD": "Re-enter password",
      "REENTER_PASSWORD_ERROR": "Re-enter password is required",
      "PASSWORD_NOT_MATCH": "Password doesn't match.",
      "LINK_SENT":
          "Link to reset password is sent to your Email. Click on the link to reset.",
      "PASSWORD_CHANGED": "Password changed successfully",
      "EARN_CASH_TITLE": "Invite & earn",
      "FRIEND_SIGNUP_TEXT":
          "When a friend signs up with your referral code, he will get ₹",
      "VERIFY_EMAIL_MOBILE":
          "Verify your email and mobile number and share referral code with your friends.",
      "FRIEND_MOBILE_VERIFIED":
          "Make sure your friend also verifies his email and mobile number.",
      "USER_GETS_BONUS_TEXT_1": "You will get ₹",
      "USER_GETS_BONUS_TEXT_2":
          "into your unreleased bonus, Which will be released in packets based on your friend's spendings.",
      "EARN_RS": "Share and earn ₹",
      "GIVE_RS": "Give ₹",
      "COPIED": "Copied to clipboard",
      "COPY_CODE": "Copy code",
      "SHARE_NOW": "Share now",
      "FROM": "From",
      "TO": "To",
      "SWITCH_FROM": "You are switching team from",
      "SOMETHING_WENT_WRONG":
          "Something went wrong please check your inputs or internet connection.",
      "REQUEST_OTP": "Request OTP",
      "OTP_SENT": "OTP to reset password is sent to your mobile.",
      "PASSWORD_SHOULD": "Password should have a ",
      "MIN_CHAR": "minimum of 8 characters, ",
      "ATLEAST_NUMBER":"Atleast 1 number, ",
      "ATLEAST_ALPHABET": "Atleast 1 alphabet and ",
      "ATLEAST_SPECIAL_CHARACTER": "Atleast 1 special character."
    };
  }
}
